# -*- coding: utf-8 -*-
"""Ensemble.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y3dAKURHe0UtghqqxQXdMUtewM83xQMI

Loading in Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
import numpy as np
import subprocess
import pandas as pd
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
#from sklearn.feature_extraction.text import CountVectorizer  #DT does not take strings as input for the model fit step....
from IPython.display import Image
#import pydotplus as pydot
from sklearn import tree
warnings.filterwarnings('ignore')
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

"""# **Date Cleaning and Loading**

**cleaning and doing one hot encoding**
"""

from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/MyDrive/Colab Notebooks/Machine Learning/FINAL PROJECT/my_training_data(in).csv'
data = pd.read_csv(path)
labels_dict={'attack':1, 'benign':0}
data['label2'] = data['label2'].map(labels_dict)
data = data.dropna()
data = data.drop('label', axis=1)
data.head()

X = data.drop('label2', axis=1)
Y = data.pop('label2')
x_train, x_test, y_train, y_test = train_test_split(X, Y,
                                                    test_size=0.3,
                                                    random_state=123,
                                                    shuffle=True)

"""## Model's

**Support Vector Machine**
"""

from sklearn.svm import SVC
svm_model = SVC(kernel='linear', C=100, gamma = 1)
svm_model.fit(x_train, y_train)

"""**KNN**"""

from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train.values, y_train.values)

"""**Random Forest**"""

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(x_train, y_train)
predictionTree = rf_model.predict(x_test)

"""# Voting Classifier"""

from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

svm_model = SVC(kernel='linear', C=100, gamma=1, probability=True)
knn_model = KNeighborsClassifier(n_neighbors=5)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
voting_clf = VotingClassifier(
    estimators=[('svm', svm_model), ('knn', knn_model), ('rf', rf_model)],
    voting='soft'
)
voting_clf.fit(x_train, y_train)
predictions = voting_clf.predict(x_test)

print(classification_report(y_test, predictions))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

#  'attack': 1, 'benign': 0
label_names = [name for name, val in sorted(labels_dict.items(), key=lambda item: item[1])]

cm = confusion_matrix(y_test, predictions, labels=y_test.unique())
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=label_names)
disp.plot()

"""# Stacking Classifier"""

from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

estimators = [
    ('svm', SVC(probability=True)),
    ('knn',KNeighborsClassifier()),
    ('rf', RandomForestClassifier())
]
stack_clf = StackingClassifier(
    estimators = estimators,
    final_estimator = LogisticRegression()
)
stack_clf.fit(x_train,y_train)

predictionsStack = stack_clf.predict(x_test)
print(classification_report(y_test, predictionsStack))
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

#  'attack': 1, 'benign': 0
label_names = [name for name, val in sorted(labels_dict.items(), key=lambda item: item[1])]

cm = confusion_matrix(y_test, predictions, labels=y_test.unique())
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=label_names)
disp.plot()

"""# Bagging Classifier"""

from sklearn.ensemble import BaggingClassifier
bag_dt = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=50)
bag_dt.fit(x_train,y_train)
print(classification_report(y_test, bag_dt.predict(x_test)))

bag_knn = BaggingClassifier(estimator=KNeighborsClassifier(n_neighbors=5), n_estimators=50)
bag_knn.fit(x_train, y_train)
print(classification_report(y_test, bag_knn.predict(x_test)))

bag_svm = BaggingClassifier(estimator=SVC(), n_estimators=10)
bag_svm.fit(x_train, y_train)
print(classification_report(y_test, bag_knn.predict(x_test)))



"""# Summary

The Stacking Classifier worked best.
It produced a model with an accuracy of 98%
"""